#!/bin/bash

gn=$( echo $1 | cut -d'.' -f1 )
if [ -n "$1" ]
then
if [ ! -f "$PWD"/UMU-GAME-ID.txt ]
then
for l in $(wget -q -O - "https://github.com/Open-Wine-Components/umu-database/raw/refs/heads/main/umu-database.csv" | sed 's/ //g' | sed 's/:/,/g')
do
if [ "$( echo $l | cut -d',' -f1 )" == "$gn" ]
then
printf "\n
$( echo $l | cut -d',' -f1 ) ✔️ $gn found
"
gi=$( echo $l | grep -E -wo 'umu.[^ ]*' | cut -d',' -f1 )
else
if [ -n "$gi" ]
then
break
fi
printf "\n$( echo $l | cut -d',' -f1 ) ❌$gn"
fi
done
if [ -z "$gi" ]
then
gi=0
fi
printf "$gi" > "$PWD"/UMU-GAME-ID.txt
fi
export WINEPREFIX=""$PWD"/.wp"
export GAMEID=$(cat "$PWD"/UMU-GAME-ID.txt)
export PROTONPATH=GE-Proton
printf "
WINEPREFIX=$WINEPREFIX
GAMEID=$GAMEID
PROTONPATH=$PROTONPATH

"
umu-run "$PWD"/"$1"
else
printf ' ------------------------
 |give a game executable|
 ------------------------
'
fi
